/**
 *
 * @author mounika,hari
 */
package com.adaptive.view;

import com.adaptive.entities.MainClass;
import com.adaptive.entities.OneTimePassword;
import com.adaptive.entities.Question;
import com.adaptive.manager.StudentManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import org.springframework.stereotype.Component;
import com.adaptive.entities.Student;
import com.adaptive.entities.TestDetail;
import com.adaptive.utility.PlaySound;
import static com.adaptive.utility.PlaySound.sound;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.temporal.ChronoUnit;
import java.time.temporal.TemporalAmount;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import javax.swing.Timer;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import sun.audio.AudioPlayer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



@Component
public class TestFrame extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form A
     */
    
    @Autowired
    StudentManager manager;
     
    @Autowired
    SpellingTest spellTest;
    
    public TestDetail testDetail = null;
    
    
   public List<Question> questionList = new ArrayList<>();
   public static int indexQuestion = 0;
   public String testCategory = null;
   private int minutes = 2;
   private int second = 60;
   public static int totalTime = 14;
   Timer timer = new Timer(1000, this);
   
   
   
   
    public List<Question> getQuestionList() {
        return questionList;
    }

    public void setQuestionList(List<Question> questionList) {
        this.questionList = questionList;
    }
    
    
    
    public TestFrame() {
        initComponents();
        group.add(jRadioButton1);
        group.add(jRadioButton2);
        group.add(jRadioButton3);
        group.add(option1Radio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        headingLabel = new javax.swing.JLabel();
        questionLabel = new javax.swing.JLabel();
        option1Radio = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        timeLabel = new javax.swing.JLabel();
        buttonCategory1 = new javax.swing.JButton();
        buttonCategory2 = new javax.swing.JButton();
        totalTimeLabel = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headingLabel.setText("Adaptive Test");

        questionLabel.setText("jLabel2");

        jButton1.setText("Submit Test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Next Question");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Submit Answer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        timeLabel.setText("jLabel1");

        buttonCategory1.setText("MATHS");

        buttonCategory2.setText("SPELLING");
        buttonCategory2.setEnabled(false);

        totalTimeLabel.setText("jLabel1");

        jButton4.setText("Writing");
        jButton4.setEnabled(false);

        jButton5.setText("Listening");
        jButton5.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 630, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeLabel)
                    .addComponent(totalTimeLabel))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(option1Radio)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonCategory1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonCategory2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(totalTimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeLabel)
                .addGap(31, 31, 31)
                .addComponent(headingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCategory1)
                    .addComponent(buttonCategory2)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(option1Radio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        indexQuestion = indexQuestion + 1;    
        this.showQuestion(indexQuestion);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jRadioButton1.isSelected())
        {
        this.questionList.get(indexQuestion).setSelectedOption(jRadioButton1.getText());
        }
        if(jRadioButton2.isSelected())
        {
        this.questionList.get(indexQuestion).setSelectedOption(jRadioButton2.getText());
        }
        if(jRadioButton3.isSelected())
        {
        this.questionList.get(indexQuestion).setSelectedOption(jRadioButton3.getText());
        }
        if(option1Radio.isSelected())
        {
        this.questionList.get(indexQuestion).setSelectedOption(option1Radio.getText());
        }
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //submit test
        try{
        testDetail = new TestDetail();
        testDetail.setQuestionWithAnswer(this.questionList);
        testDetail.setCategory(testCategory);
        testDetail.setMinutes(String.valueOf(getMinutesTaken()));
        testDetail.setSecond(String.valueOf(getSecondTaken()));
        manager.submitTest(testDetail);
        timer.stop();
        JOptionPane.showMessageDialog(this, "Test Submitted Successfully");
        askForNextCategoryTest();
        
        }catch(Exception e)
        {
        e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCategory1;
    private javax.swing.JButton buttonCategory2;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    public javax.swing.JRadioButton jRadioButton1;
    public javax.swing.JRadioButton jRadioButton2;
    public javax.swing.JRadioButton jRadioButton3;
    public javax.swing.JRadioButton option1Radio;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel totalTimeLabel;
    // End of variables declaration//GEN-END:variables
    ButtonGroup group = new ButtonGroup();
  
    public JLabel getHeadingLabel() {
        return headingLabel;
    }

    public void setHeadingLabel(JLabel headingLabel) {
        this.headingLabel = headingLabel;
    }

     public void showQuestion(int index) {
         try{
       this.questionLabel.setText(this.questionList.get(index).getQuestion());
       this.jRadioButton1.setText(this.questionList.get(index).getOption1());
       this.jRadioButton2.setText(this.questionList.get(index).getOption2());
       this.jRadioButton3.setText(this.questionList.get(index).getOption3());
       this.option1Radio.setText(this.questionList.get(index).getOption4());
       this.testCategory = this.questionList.get(index).getCategory();
       }catch(IndexOutOfBoundsException excp)
         {
                excp.printStackTrace();
         }
    }

    public void startTime(){
        timer.setInitialDelay(0);
        timer.start();
    }

    @Override
    public void actionPerformed(ActionEvent e) {
            second = second - 1;
            if(second <= 0)
            {
                if(minutes <= 0)
                {
                    PlaySound.stop();
                    JOptionPane.showMessageDialog(this, "Test time is over!! Test will submit automatically ");
                    jButton1ActionPerformed(null);
                    this.timer.stop();
                    this.dispose();
                }
                minutes = minutes -1 ; 
                totalTime = totalTime -1;
                second = 60;
            }
            if(minutes == 0)
                {
                   timeLabel.setForeground(Color.red);
                    PlaySound.play(PlaySound.alert_file);
               }
            timeLabel.setText("00:"+minutes+":"+second);
            totalTimeLabel.setText("00:"+totalTime+":"+second);
    }

   

    private void askForNextCategoryTest() {
    int status =  JOptionPane.showConfirmDialog(this, "Do you want to start next test ?");
    System.out.print(status);
    if(status == 0)
    {
        try {
            List<Question> questionList = manager.getTestPaper("2");
            spellTest.setQuestionList(questionList);
            spellTest.showQuestion(spellTest.indexQuestion);
            spellTest.setVisible(true);
            spellTest.startTime();
            spellTest.mathsButton.setToolTipText(testDetail.getMinutes() + ":" + testDetail.getSecond());
            this.dispose();
            
        } catch (Exception ex) {
            Logger.getLogger(TestFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }else
    {
        this.dispose();
    }
    }

    public int getMinutesTaken() {
            return 2 - this.minutes;
    }

    public int getSecondTaken() {
            return 60 - this.second;
            
    }
   
  
     
  
}
